
Welcome to CRISPRDirection [version 2.0].
---------------------
	CRISPRDirection_v2.0.pl program requires a Unix based operating system. It should run without any error in both Linux (Red hat 5, Fedora-14) and Mac OS (Version-10.6.8). 
	However, Mac OS users should check the 'RNAfold' [comes with vienna RNA package], 'seqret' and 'water' [comes with Emboss-tools] installation.
	Simply issue the command to see if the program is running from the current directory:

	perl CRISPRDirection_v2.0.pl -h


Important Note:
---------------------
	If you already have 'RNAfold', 'seqret', and 'water' installed and accessible, then you probably don't need anything else. Alternately, 
	You need to have Emboss tools (version 6.3.1 or higher) and Vienna RNA package (version 2.0.7 or higher) installed. The 'other_executables' 
	folder contains the executables of RNAfold, water and seqret but they may not work with your version of Linux. Check each of them by the 
	following commands from the current directory:
	
	./other_executables/RNAfold -h
	
	./other_executables/water -h
	
	./other_executables/seqret -h
	
	If you see all the programs are running successfully, then copying them to a location like '/usr/local/bin' [require root access] will 
	solve the issue. Alternately, export the 'other_executables' folder to your path will also work. To know how to export a directory refer
	this http://www.troubleshooters.com/linux/prepostpath.htm


1. How to use the program:
---------------------
	* Open a terminal and move to this folder. Then issue a command from the terminal like this:
		
		perl CRISPRDirection_v2.0.pl -r test_repeats.fa -o output.txt
 		
		or
		
		perl CRISPRDirection_v2.0.pl -f test.fa

		or
		
		perl CRISPRDirection_v2.0.pl -g NC_017625.gbk


	* For mode detailed help with the options run:		
		
		perl CRISPRDirection_v2.0.pl -h

2. Dependencies:
---------------------
	* You must have a working perl installation (comes with pre-installed in most operating system except Windows).

	* RNAfold: RNAfold comes with Vienna RNA package and is required (http://www.tbi.univie.ac.at/RNA/) for method 
	  "Analysis of RNA secondary structure". If you don't have a pre-installed working version of RNAfold, you should
	  install RNAfold program from http://www.tbi.univie.ac.at/~ronny/RNA/index.html#download.

	  For more details on installation please refer to http://www.tbi.univie.ac.at/RNA/INSTALL.html

	* CRISPRDirection uses 'water' and 'seqret' from EMBOSS tools. These executables are already supplied with this disribution 
	  and should work on any Unix based operating system. However, if that doesn't work, please follow the instructions from
	  http://emboss.sourceforge.net/download/ to get and install EMBOSS tools. Once installed, copy and replace 'water' and 
	  'seqret' executable from the relative installation directory (e.g. /usr/local/bin) to the current directory.

	* CRISPR arrays are predicted by both PILER-CR and CRT. Both the executable are provided with this distribution. However 
	  if either of them doesn't work, you should obtain a working version of PILER-CR (http://www.drive5.com/pilercr/) and 
	  CRT (http://www.room220.com/crt/) and replace the existing version of the program.
	  
	  #-- Note: If the directory name of the version differes, then modify the CRISPRDirection_v1.pl script accordingly.      




3. Folders in this directory:
---------------------
	* Supplement: The Supplement folder contains files that were used in the CRISPRDirection analysis. These files are for researchers 
	  who might be interrested in doing detail analysis of the individual methods. The CRISPRDirection program does not require the files.
	
	* Ref_lib_files: This folder contains the file 'verified_repeats_with_family.txt' which contains all 25 known repeats.

	* tmp: This folder is for holding temporary files that are generated by CRISPRDirection_v1.pl program during execution. Please allow 
	  Read and Write permission to this folder for all dependent programs as well as CRISPRDirection_v1.pl (e.g. 'chmod 775 tmp' should be enough).
	
	* pilercr1.06: contains PILER-CR executable and other related files.


4. Files apart from CRISPRDirection_v2.0.pl and README: 
---------------------
	* Third party executables:  RNAfold, seqret, water and CRT1.2-CLI.jar
	
	*  test.fa : Test genomic sequence in fasta format.

	* test_repeats.fa: Only repeats in FASTA format.

	* NC_017625.gbk : A sample annotation file which also contains genomic sequence. You can download GBK friles from NCBI ftp (ftp://ftp.ncbi.nlm.nih.gov/genomes/Bacteria/),
	  for all other ways (like http://www.ncbi.nlm.nih.gov/nuccore/NC_017625 ), click on send, select 'Complete Record', Choose Destination 'File',and Download format 'GenBank (Full)'.

	* reference_output.txt : This is a sample reference output file, contains the CRISPR arrays and directional analysis summary of 'NC_017625'.   	







